apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "backbeat.fullname" . }}-consumer
  labels:
    app: {{ template "backbeat.name" . }}-replication
    chart: {{ template "backbeat.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replication.consumer.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "backbeat.name" . }}-replication
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "backbeat.fullname" . }}-consumer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/src/app/docker-entrypoint.sh"]
          args: ["npm", "run", "queue_processor"]
          env:
            - name: EXTENSIONS_REPLICATION_SOURCE_S3_HOST
              value: "{{- printf "%s-cloudserver-front" .Release.Name | trunc 63 | trimSuffix "-" -}}"
            - name: EXTENSIONS_REPLICATION_DEST_BOOTSTRAPLIST
              value: "{{- printf "%s-cloudserver-front:80" .Release.Name | trunc 63 | trimSuffix "-" -}}"
            - name: MONGODB_HOSTS
              value: "{{ .Release.Name }}-mongodb-replicaset-0.{{ .Release.Name }}-mongodb-replicaset:27017,{{ .Release.Name }}-mongodb-replicaset-1.{{ .Release.Name }}-mongodb-replicaset:27017,{{ .Release.Name }}-mongodb-replicaset-2.{{ .Release.Name }}-mongodb-replicaset:27017"
            - name: REDIS_HOST
              value: "{{- printf "%s-%s" .Release.Name "redis" | trunc 63 | trimSuffix "-" -}}"
          {{ template "backbeat.common" . | indent 12 }}
          {{- range $key, $value := .Values.env }}
            - name: {{ $key | upper | replace "." "_" }}
              value: {{ $value | quote }}
          {{- end }}
          {{- range $key, $value := .Values.replication.consumer.env }}
            - name: {{ $key | upper | replace "." "_" }}
              value: {{ $value | quote }}
          {{- end }}
          # TODO livenessProbe:
          # TODO readinessProbe:
          resources:
{{ toYaml .Values.replication.consumer.resources | indent 12 }}
    {{- with .Values.replication.consumer.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.replication.consumer.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.replication.consumer.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
