---

version: "3"

services:
  s3:
    image: scality/s3server
    ports:
      - "8000"

  lb:
    image: scality/nginx-lb
    ports:
      - "80:80"
    environment:
      LISTEN_PORT: 80
      UPSTREAM_SERVER: s3
