---
apiVersion: zenko.io/v1alpha1
kind: ZenkoVersion
metadata:
  name: 1.1-dev
spec:
  imagePullPolicy: Always
  versions:
    cloudserver:
      image: registry.scality.com/zenko-dev/cloudserver
      tag: latest-8.1.2
    backbeat:
      image: registry.scality.com/zenko-dev/backbeat
      tag: 161b9c1
    blobserver:
      image: registry.scality.com/sf-eng/blobserver
      tag: 1.0.8
    jabba:
      image: registry.scality.com/sf-eng/jabba
      tag: 940d
    secureChannelProxy:
      image: registry.scality.com/zenko-dev/cloudserver
      tag: 4332d0a
    localData:
      image: zenko/cloudserver
      tag: 8.1.15
    metrics:
      image: registry.scality.com/zenko-dev/cloudserver
      tag: 4332d0a
    s3utils:
      image: zenko/s3utils
      tag: 1.2
    zookeeper:
      image: pravega/zookeeper
      tag: 0.2.4
    kafka:
      image: wurstmeister/kafka
      tag: 2.12-2.3.0
    shell:
      image: busybox
      tag: 1.31.0-glibc
    mongodb: 4.0
    redis: 5.0.3-v1
