apiVersion: v1
kind: Service
metadata:
  name: {{ template "zookeeper.fullname" . }}
  labels:
    app: {{ template "zookeeper.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 2181
      protocol: TCP
      name: {{ .Values.service.name }}
  clusterIP: None
  selector:
    app: {{ template "zookeeper.name" . }}
    release: {{ .Release.Name }}
