{{- if .Values.maintenance.debug.enabled -}}
apiVersion: v1
kind: Pod
metadata:
  name: {{ template "zenko.debug" . }}-kafka-client
  labels:
{{ include "zenko.labels.standard" . | indent 4 }}
spec:
  containers:
  - name: kafkaclient
    image: {{ .Values.maintenance.kafkaClientImage.repository }}:{{ .Values.maintenance.kafkaClientImage.tag }}
    imagePullPolicy: {{ .Values.maintenance.kafkaClientImage.pullPolicy }}
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
    env:
    - name: ZOOKEEPER_URL
      value: "{{ .Release.Name }}-zenko-quorum:2181"
{{- end -}}
