{{- if .Values.maintenance.debug -}}
apiVersion: v1
kind: Pod
metadata:
  name: {{ template "zenko.fullname" . }}-debug-s3utils
spec:
  containers:
  - name: utils
    image: {{ .Values.maintenance.image.repository }}:{{ .Values.maintenance.image.tag }}
    imagePullPolicy: {{ .Values.maintenance.image.pullPolicy }}
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
{{- end -}}
