apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "wormhole.ftpd.fullname" . }}
  labels:
    app: {{ template "wormhole.name" . }}
    chart: {{ template "wormhole.chart" . }}
    component: ftpd
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.ftpd.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "wormhole.name" . }}
      component: ftpd
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "wormhole.name" . }}
        component: ftpd
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.ftpd.image.repository }}:{{ .Values.ftpd.image.tag }}"
          imagePullPolicy: {{ .Values.ftpd.image.pullPolicy }}
          env:
            - name: FTP_SERVER_NAME
              value: {{ .Values.ftpd.ftp.servername }}
            - name: FTP_USERNAME
              value: {{ .Values.ftpd.ftp.username }}
            - name: FTP_PASSWORD
              value: {{ .Values.ftpd.ftp.password }}
            - name: AWS_REGION
              value: {{ .Values.ftpd.remote.region }}
            - name: AWS_BUCKET_NAME
              value: {{ .Values.ftpd.remote.bucket }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.ftpd.remote.accessKey }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.ftpd.remote.secretKey }}
            - name: AWS_ENDPOINT
              value: {{ .Values.ftpd.remote.endpoint }}
            - name: PASSIVE_PORT_START
              value: "{{ .Values.ftpd.ftp.passive.start }}"
            - name: PASSIVE_PORT_END
              value: "{{ .Values.ftpd.ftp.passive.end }}"
            - name: FORCE_PATH_STYLE
              value: "true"
          ports:
            - name: ftp
              containerPort: 21
              protocol: TCP
{{- $passive_start := int .Values.ftpd.ftp.passive.start -}}
{{- $passive_end := int .Values.ftpd.ftp.passive.end -}}
{{ range $i := untilStep $passive_start $passive_end 1 }}
            - name: passive-{{ $i }}
              containerPort: {{ $i }}
              protocol: TCP
{{- end -}}
