ingress:
  enabled: true
  hosts:
    - ""

zenko-queue:
  replicas: 1
  kafkaHeapOptions: "-Xms256M"
  configurationOverrides:
    "offsets.topic.replication.factor": 1
    "min.insync.replicas": 1

zenko-quorum:
  replicaCount: 1
  env:
    ZK_HEAP_SIZE: "256M"

mongodb-replicaset:
  replicaSet: rs0
  replicas: 3

redis-ha:
  replicas:
    servers: 1
    sentinels: 1
