zenko-zookeeper:

kafka:
  replicas: 3
  configurationOverrides:
     "offsets.topic.replication.factor": 3
  persistentVolume:
    enabled: true

s3-data:
  persistentVolume:
    enabled: true
    accessModes:
    - ReadWriteOnce

s3-metadata:
  persistentVolume:
    enabled: true
