dependencies:
# Upstream `zenko-*` Charts
- name: zenko-zookeeper
  version: "0.0.3"
  repository: "https://scality.github.io/zenko-zookeeper/charts"

# Upstream Kubernetes Charts
- name: prometheus
  version: "5.0.2"
  repository: "https://kubernetes-charts.storage.googleapis.com/"
