dependencies:
# Upstream Kubernetes Charts
- name: kafka
  version: "0.7.1"
  repository: "http://storage.googleapis.com/kubernetes-charts-incubator"
  alias: zenko-queue
- name: zookeeper
  version: "1.0.0"
  repository: "http://storage.googleapis.com/kubernetes-charts-incubator"
  alias: zenko-quorum
- name: grafana
  version: "1.11.6"
  repository: "https://kubernetes-charts.storage.googleapis.com/"
  condition: grafana.enabled

# Charts managed in this repository
- name: backbeat
  version: "1.0.0"
  repository: "file://../backbeat"
- name: s3-data
  version: "1.0.0"
  repository: "file://../s3-data"
- name: cloudserver
  version: "1.0.0"
  repository: "file://../cloudserver"
- name: zenko-nfs
  version: "1.0.0"
  repository: "file://../zenko-nfs"
  condition: zenko-nfs.enabled
- name: prometheus
  version: "8.0.0-Z"
  repository: "file://../prometheus"
  condition: prometheus.enabled
- name: mongodb-replicaset
  version: "3.5.2-Z"
  repository: "file://../mongodb-replicaset"
- name: redis-ha
  version: "3.0.0-Z"
  repository: "file://../redis-ha"
  condition: redis-ha.enabled

