apiVersion: v1
kind: Service
metadata:
  name: aws-mock
spec:
  selector:
    name: aws-mock
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Pod
metadata:
  name: aws-mock-pod
  labels:
    name: aws-mock
spec:
  containers:
  - image: zenko/cloudserver:latest
    name: aws-mock
    ports:
      - containerPort: 80
    imagePullPolicy: Always
    env:
    - name: REMOTE_MANAGEMENT_DISABLE
      value: "1"
    - name: ENDPOINT
      value: "aws-mock"
    ports:
    - name: http
      containerPort: 8000
