apiVersion: v1
kind: Pod
metadata:
  name: "zenko-test-pod"
spec:
  hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "kubernetes"
  containers:
  - name: aggressor
    image: zenko/zenko-releng:0.0.10
    imagePullPolicy: Always
    resources:
      requests:
        cpu: "1"
        memory: 2Gi
      limits:
        cpu: "1"
        memory: 2Gi
    command: ["/bin/sh", "-c", "buildbot-worker create-worker . ${BUILDMASTER}:${BUILDMASTER_PORT} ${WORKERNAME} ${WORKERPASS} && buildbot-worker start --nodaemon"]
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-socket
  - name: ssh-forward
    image: "{{ images['ssh-forward'] }}"
    resources:
      requests:
        cpu: "500m"
        memory: "500Mi"
      limits:
        cpu: "500m"
        memory: "500Mi"
    env:
    - name: SSH_PRIVATE_KEY
      value: "%(secret:metalk8s_bootstrap_ssh_key)s"
    - name: SSH_CONFIG
      value: "%(secret:metalk8s_bootstrap_ssh_config)s"
    args: ['/bin/sh', '-c', 'ssh -NT bootstrap']
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket
