# Default values for backbeat.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: arekisannda/backbeat
  tag: latest
  pullPolicy: IfNotPresent

orbit:
  enabled: false
  endpoint: https://api.zenko.io

api:
  replicaCount: 1
  service:
    name: backbeat-api
    type: ClusterIP

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

  nodeSelector: {}
  tolerations: []
  affinity: {}

replication:
  consumer:
    replicaCount: 1

    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

  producer:
    replicaCount: 1

    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

  status:
    replicaCount: 1

    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
