apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "zenko-grafana.fullname" . }}
  labels:
    app: {{ template "zenko-grafana.name" . }}
    chart: {{ template "zenko-grafana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "zenko-grafana.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "zenko-grafana.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GF_SESSION_PROVIDER
              value: memory
            - name: GF_ANALYTICS_REPORTING_ENABLED
              value: "false"
            - name: GF_ANALYTICS_CHECK_FOR_UPDATES
              value: "false"
            - name: GF_LOG_MODE
              value: console
          volumeMounts:
            - name: config-provisioning-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: config-provisioning-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
            - name: config-dashboards
              mountPath: /etc/grafana/dashboards
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 30
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: config-provisioning-datasources
          configMap:
            name: {{ template "zenko-grafana.fullname" . }}-provisioning-datasources
        - name: config-provisioning-dashboards
          configMap:
            name: {{ template "zenko-grafana.fullname" . }}-provisioning-dashboards
        - name: config-dashboards
          configMap:
            name: {{ template "zenko-grafana.fullname" . }}-dashboards
