version: "3.4"

services:
  s3-data:
    image: zenko/cloudserver:pensieve-3
    ports:
      - 9991
    networks:
      - backend
    environment:
      S3DATAPATH: /data
      LISTEN_ADDR: 0.0.0.0
    volumes:
      - "s3-data:/data:rw"
    command: npm run start_dataserver
    deploy:
      placement:
        constraints:
          - node.labels.io.zenko.type == storage

  s3-front:
    image: zenko/cloudserver:pensieve-3
    ports:
      - 8000
    networks:
      backend:
        aliases:
          - zenko-cloudserver-replicator
      frontend-dmz:
    environment:
      DATA_HOST: s3-data
      REDIS_HOST: cache
      ENDPOINT: "${ENDPOINT:-zenko}"
      REMOTE_MANAGEMENT_DISABLE: "${REMOTE_MANAGEMENT_DISABLE:-0}"
      S3METADATA: mongodb
      MONGODB_HOSTS: 'mongodb:27017'
      MONGODB_RS: rs0
      CRR_METRICS_HOST: backbeat-api
      CRR_METRICS_PORT: 8900
    secrets:
      - s3-credentials
    command: >-
      dockerize
        -timeout 90s
        -wait tcp://s3-data:9991
        -wait tcp://backbeat-api:8900
        -wait tcp://cache:6379
        -wait tcp://mongodb:27017
        --
      npm run start_s3server
    deploy:
      mode: replicated
      update_config:
        parallelism: 1
        delay: "10s"
        monitor: "5s"

  mongodb:
    image: mongo:3.4.14-jessie
    volumes:
      - 'mongodb-data:/data/db'
    networks:
      - backend
    ports:
      - 27017
    command: mongod --replSet rs0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.io.zenko.type == storage

  mongodb-init:
    image: mongo:3.4.14-jessie
    networks:
      - backend
    command: >-
      mongo 'mongodb:27017' --eval
        "rs.initiate({ _id : 'rs0', members: [ { _id: 0, host: 'mongodb:27017' } ] })"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  cache:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - backend

  lb:
    image: zenko/loadbalancer
    ports:
      - "80:80"
    environment:
      LISTEN_PORT: 80
      UPSTREAM_SERVER: "s3-front:8000"
    networks:
      - frontend
      - frontend-dmz
    depends_on:
      - s3-front
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: "10s"
        monitor: "5s"

  queue:
    image: 'wurstmeister/kafka:1.0.0'
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: queue
      KAFKA_CREATE_TOPICS: 'backbeat-replication:1:1,backbeat-replication-status:1:1,backbeat-metrics:1:1'
      KAFKA_ZOOKEEPER_CONNECT: 'quorum:2181'
      KAFKA_HEAP_OPTS: '-Xmx512M'
      KAFKA_LOG_DIRS: /kafka/kafka-logs
    ports:
      - 9092
    networks:
      - backend
    volumes:
      - "queue-journal:/kafka:rw"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.io.zenko.type == storage

  quorum:
    image: 'zookeeper:3.4.11'
    ports:
      - 2181
    networks:
      - backend
    volumes:
      - "quorum-data:/data:rw"
      - "quorum-datalog:/datalog:rw"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.io.zenko.type == storage

  backbeat-producer:
    image: 'zenko/backbeat:pensieve-4'
    command: >-
      dockerize
        -timeout 90s
        -wait tcp://quorum:2181
        -wait tcp://queue:9092
        -wait tcp://mongodb:27017
        --
      npm run queue_populator
    environment:
      ZOOKEEPER_AUTO_CREATE_NAMESPACE: 1
      ZOOKEEPER_CONNECTION_STRING: 'quorum:2181'
      KAFKA_HOSTS: 'queue:9092'
      MONGODB_HOSTS: 'mongodb:27017'
      MONGODB_RS: 'rs0'
      REDIS_HOST: cache
      REDIS_PORT: 6379
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1

  backbeat-api:
    image: 'zenko/backbeat:pensieve-4'
    command: >-
      dockerize
        -timeout 90s
        -wait tcp://cache:6379
        -wait tcp://quorum:2181
        -wait tcp://queue:9092
        --
      npm start
    environment:
      ZOOKEEPER_AUTO_CREATE_NAMESPACE: 1
      ZOOKEEPER_CONNECTION_STRING: 'quorum:2181'
      KAFKA_HOSTS: 'queue:9092'
      REDIS_HOST: cache
      REDIS_PORT: 6379
      HEALTHCHECKS_ALLOWFROM: '0.0.0.0/0'
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1

  backbeat-consumer:
    image: 'zenko/backbeat:pensieve-4'
    command: >-
      dockerize
        -timeout 90s
        -wait tcp://quorum:2181
        -wait tcp://queue:9092
        -wait tcp://zenko-cloudserver-replicator:8000
        -wait tcp://mongodb:27017
        --
      npm run queue_processor
    environment:
      ZOOKEEPER_AUTO_CREATE_NAMESPACE: 1
      ZOOKEEPER_CONNECTION_STRING: 'quorum:2181'
      KAFKA_HOSTS: 'queue:9092'
      EXTENSIONS_REPLICATION_SOURCE_AUTH_TYPE: 'service'
      EXTENSIONS_REPLICATION_SOURCE_AUTH_ACCOUNT: 'service-replication'
      EXTENSIONS_REPLICATION_SOURCE_S3_HOST: 'zenko-cloudserver-replicator'
      EXTENSIONS_REPLICATION_SOURCE_S3_PORT: 8000
      EXTENSIONS_REPLICATION_DEST_AUTH_TYPE: 'service'
      EXTENSIONS_REPLICATION_DEST_AUTH_ACCOUNT: 'service-replication'
      EXTENSIONS_REPLICATION_DEST_BOOTSTRAPLIST: 'zenko-cloudserver-replicator:8000'
      MONGODB_HOSTS: 'mongodb:27017'
      MONGODB_RS: 'rs0'
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1

networks:
  backend:
  frontend:
  frontend-dmz:

volumes:
  s3-data:
  mongodb-data:
  queue-journal:
  quorum-data:
  quorum-datalog:

secrets:
  s3-credentials:
    file: ./secrets.txt
