ingress:
  enabled: true

maintenance:
  # Both options are enabled to test templating
  enabled: true
  retryFailed:
    schedule: "* 23 * * *"
  retryPending:
    schedule: "* 23 * * *"
  debug:
    enabled: true

cosmos:
  ci: true
  storageClass: ci-zenko
  rbac:
    namespaced: true
  operator:
    image:
      pullPolicy: Always
  scheduler:
    image:
      pullPolicy: Always

s3-data:
  persistentVolume:
    enabled: false

mongodb-replicaset:
  persistentVolume:
    enabled: false

prometheus:
  rbac:
    create: false
  serviceAccounts:
    alertmanager:
      name: default
      create: false
    nodeExporter:
      name: default
      create: false
    kubeStateMetrics:
      name: default
      create: false
    pushgateway:
      name: default
      create: false
    server:
      name: default
      create: false
  server:
    persistentVolume:
      enabled: false

zenko-queue:
  persistence:
    enabled: false
  rbac:
    enabled: false

zenko-quorum:
  persistence:
    enabled: false

redis-ha:
  persistentVolume:
    enabled: false
  rbac:
    create: false
  serviceAccount:
    create: false
    name: default

global:
  orbit:
    endpoint: "http://ciutil-orbit-simulator:4222"
    managerMode: "poll"
    workerMode: "poll"

cloudserver:
  image:
    pullPolicy: Always
  replicaCount: 3
  replicaFactor: 1
  env:
    MPU_TESTING: 'yes'
    PUSH_STATS: 'false'
    CI_CEPH: 'true'
    CI: 'true'
    S3_END_TO_END: 'true'

backbeat:
  image:
    pullPolicy: Always
  replication:
    replicaFactor: 2
    retry:
      aws_s3:
        timeoutS: 900
        maxRetries: 5
        backoff:
          min: 2000
          max: 10000
          jitter: 0.1
          factor: 1.5
      azure:
        timeoutS: 900
        maxRetries: 5
        backoff:
          min: 2000
          max: 10000
          jitter: 0.1
          factor: 1.5
      gcp:
        timeoutS: 900
        maxRetries: 5
        backoff:
          min: 2000
          max: 10000
          jitter: 0.1
          factor: 1.5
  lifecycle:
    conductor:
      cronRule: "* * * * *"

grafana:
  persistentVolume:
    enabled: false
  rbac:
    create: false
    pspEnabled: false
  serviceAccount:
    create: false
  adminUser: admin
  adminPassword: strongpassword
