---
version: "0.2"

branches:
  documentation/*, feature/*, improvement/*, bugfix/*, w/*, q/*, hotfix/*:
    stage: pre-merge

models:
  - Git: &git_pull
      name: git pull
      repourl: "%(prop:git_reference)s"
      mode: full
      method: clobber
      retryFetch: true
      haltOnFailure: true

stages:
  pre-merge:
    simultaneous_builds: 4
    worker:
      type: local
    steps:
    - TriggerStages:
        name: trigger all the tests
        haltOnFailure: true
        stage_names:
        - build-doc
        - build-iso

  build-doc:
    worker:
      type: kube_pod
      path: eve/workers/doc-builder.yaml
      images:
        doc-builder:
          context: 'docs'
          dockerfile: docs/Dockerfile
    steps:
    - Git: *git_pull
    - ShellCommand:
        name: 'Build doc'
        haltOnFailure: true
        command: |-
          tox --workdir /tmp/tox -e docs -- html BUILDDIR="%(prop:builddir)s/build/artifacts"
          # Building the latex twice to catch up the reference
          tox --workdir /tmp/tox -e docs -- latexpdf BUILDDIR="%(prop:builddir)s/build/artifacts"
          tox --workdir /tmp/tox -e docs -- latexpdf BUILDDIR="%(prop:builddir)s/build/artifacts"
        workdir: build/docs

    - Upload:
        name: Upload documentation
        source: 'artifacts'
        urls:
          - "html/index.html"
          - "latex/*.pdf"

  build-iso:
    worker:
      type: kube_pod
      path: eve/workers/build-iso/pod.yaml
      images:
        build-iso: eve/workers/build-iso
    steps:
    - Git: *git_pull
    - ShellCommand: *private_registry_login
    - ShellCommand:
        name: 'Build ISO'
        haltOnFailure: true
        workdir: build/solution
        command: ./build.sh
        env:
          DOCKER_SOCKET: 'http://localhost:2375'
    - Upload:
        name: Upload ISO
        source: 'solution/_build'
        urls:
          - "*.iso"
