
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "burry.fullname" . }}-config
  labels:
    app: {{ template "burry.name" . }}
    chart: {{ template "burry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  .burryfest: |-
    {
      "svc": "zk",
      "svc-endpoint": {{ include "zookeeper.endpoint" . | quote }},
      "timeout": 4000,
      "target": "{{ .Values.configMap.destType }}",
      "credentials": {
        "target-endpoint": "{{ .Values.configMap.destEndpoint }}",
        "params": [
          {
            "key": "ACCESS_KEY_ID",
            "val": "{{ .Values.configMap.accessKey }}"
          },
          {
            "key": "SECRET_ACCESS_KEY",
            "val": "{{ .Values.configMap.secretKey }}"
          },
          {
            "key": "BUCKET",
            "val": "{{ .Values.configMap.bucket }}"
          },
          {
            "key": "SSL",
            "val": "{{ .Values.configMap.ssl }}"
          }
        ]
      }
    }
