apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: zenkoversions.zenko.io
spec:
  group: zenko.io
  names:
    kind: ZenkoVersion
    listKind: ZenkoVersionList
    plural: zenkoversions
    singular: zenkoversion
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ZenkoVersion is the Schema for the zenkoversions API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ZenkoVersionSpec defines the desired state of ZenkoVersion
          properties:
            imagePullPolicy:
              description: PullPolicy describes a policy for if/when to pull a container
                image
              type: string
            versions:
              description: ZenkoVersionSpecVersions defines the set of desired images
              properties:
                backbeat:
                  description: ZenkoVersionImage defines an image repository and version
                  properties:
                    image:
                      type: string
                    tag:
                      type: string
                  type: object
                blobserver:
                  description: ZenkoVersionImage defines an image repository and version
                  properties:
                    image:
                      type: string
                    tag:
                      type: string
                  type: object
                cloudserver:
                  description: ZenkoVersionImage defines an image repository and version
                  properties:
                    image:
                      type: string
                    tag:
                      type: string
                  type: object
                jabba:
                  description: ZenkoVersionImage defines an image repository and version
                  properties:
                    image:
                      type: string
                    tag:
                      type: string
                  type: object
                kafka:
                  description: ZenkoVersionImage defines an image repository and version
                  properties:
                    image:
                      type: string
                    tag:
                      type: string
                  type: object
                localData:
                  description: ZenkoVersionImage defines an image repository and version
                  properties:
                    image:
                      type: string
                    tag:
                      type: string
                  type: object
                metrics:
                  description: ZenkoVersionImage defines an image repository and version
                  properties:
                    image:
                      type: string
                    tag:
                      type: string
                  type: object
                mongodb:
                  type: string
                redis:
                  type: string
                s3utils:
                  description: ZenkoVersionImage defines an image repository and version
                  properties:
                    image:
                      type: string
                    tag:
                      type: string
                  type: object
                secureChannelProxy:
                  description: ZenkoVersionImage defines an image repository and version
                  properties:
                    image:
                      type: string
                    tag:
                      type: string
                  type: object
                shell:
                  description: ZenkoVersionImage defines an image repository and version
                  properties:
                    image:
                      type: string
                    tag:
                      type: string
                  type: object
                zookeeper:
                  description: ZenkoVersionImage defines an image repository and version
                  properties:
                    image:
                      type: string
                    tag:
                      type: string
                  type: object
              type: object
          type: object
        status:
          description: ZenkoVersionStatus defines the observed state of ZenkoVersion
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
