{{- if and .Values.persistentVolume.enabled (not .Values.persistentVolume.existingClaim) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "cosmos.fullname" . }}
  labels:
{{ include "cosmos.labels" . | indent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: {{ .Values.persistentVolume.size }}
{{ toYaml .Values.persistentVolume.volumeConfig | indent 2 }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ template "cosmos.storageclass.name" . }}
{{- end }}
