{{- if not .Values.rclone.remote.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cosmos.rclone.fullname" . }}
  labels:
    app: {{ template "cosmos.name" . }}
    chart: {{ template "cosmos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  accessKey: {{ .Values.rclone.remote.accessKey | b64enc }}
  secretKey: {{ .Values.rclone.remote.secretKey | b64enc }}
{{- end -}}
