{{- $dst := merge (default .Values.rclone.destination .Values.rclone.remote) .Values.rclone.destination }}
{{- $src := .Values.rclone.source }}
{{- if or (not $dst.existingSecret) (not $src.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cosmos.rclone.fullname" . }}
  labels:
{{ include "cosmos.labels" . | indent 4 }}
type: Opaque
data:
  {{- if not $dst.existingSecret }}
  destinationAccessKey: {{ $dst.access_key_id | default $src.accessKey | b64enc }}
  destinationSecretKey: {{ $dst.secret_access_key | default $src.secretKey | b64enc }}
  {{- end }}
  {{- if and (ne $src.type "local") (not $src.existingSecret) }}
  sourceAccessKey: {{ $src.access_key_id | b64enc }}
  sourceSecretKey: {{ $src.secret_access_key | b64enc }}
  {{- end }}
{{- end -}}
